module.exports = [
  {
    id: 1,
    username: "cbreitbarth",
    password: "password",
    role: "agent",
    first_name: "Chiumbo",
    last_name: "Breitbarth",
    phone_number: 4294009059,
    email: "cbreitbarth@gmail.com",
  },
  {
    id: 2,
    username: "astevens",
    password: "password",
    role: "agent",
    first_name: "Aslan",
    last_name: "Stevens",
    phone_number: 1366991668,
    email: "astevens@gmail.com",
  },
  {
    id: 3,
    username: "sbakema",
    password: "password",
    role: "agent",
    first_name: "Silvina",
    last_name: "Bakema",
    phone_number: 3980033382,
    email: "sbakema@gmail.com",
  },
  {
    id: 4,
    username: "mwehner",
    password: "password",
    role: "agent",
    first_name: "Miriam",
    last_name: "Wehner",
    phone_number: 5007484403,
    email: "mwehner@gmail.com",
  },
  {
    id: 5,
    username: "nmartin",
    password: "password",
    role: "agent",
    first_name: "Nedelcho",
    last_name: "Martin",
    phone_number: 7858074122,
    email: "nmartin@gmail.com",
  },
  {
    id: 6,
    username: "tsobel",
    password: "password",
    role: "agent",
    first_name: "Tauno",
    last_name: "Sobel",
    phone_number: 1897439776,
    email: "tsobel@gmail.com",
  },
  {
    id: 7,
    username: "vtian",
    password: "password",
    role: "dispatcher",
    first_name: "Valentin",
    last_name: "Tian",
    phone_number: 2704579068,
    email: "vtian@gmail.com",
  },
  {
    id: 8,
    username: "vmartell",
    password: "password",
    role: "dispatcher",
    first_name: "Voirrey",
    last_name: "Martell",
    phone_number: 4100794364,
    email: "vmartell@gmail.com",
  },
  {
    id: 9,
    username: "vshirai",
    password: "password",
    role: "client",
    first_name: "Vanja",
    last_name: "Shirai",
    phone_number: 5771798344,
    email: "vshirai@gmail.com",
  },
  {
    id: 10,
    username: "umoser",
    password: "password",
    role: "client",
    first_name: "Uma",
    last_name: "Moser",
    phone_number: 3662776854,
    email: "umoser@gmail.com",
  },
  {
    id: 11,
    username: "emiyashita",
    password: "password",
    role: "client",
    first_name: "Eko",
    last_name: "Miyashita",
    phone_number: 8924574399,
    email: "emiyashita@gmail.com",
  },
  {
    id: 12,
    username: "ldermott",
    password: "password",
    role: "client",
    first_name: "Lya",
    last_name: "Dermott",
    phone_number: 9851477390,
    email: "ldermott@gmail.com",
  },
  {
    id: 13,
    username: "ihult",
    password: "password",
    role: "client",
    first_name: "Irene",
    last_name: "Hult",
    phone_number: 9629875549,
    email: "ihult@gmail.com",
  },
  {
    id: 14,
    username: "dmccullough",
    password: "password",
    role: "client",
    first_name: "Daniella",
    last_name: "McCullough",
    phone_number: 7208893248,
    email: "dmccullough@gmail.com",
  },
  {
    id: 15,
    username: "hthrussell",
    password: "password",
    role: "client",
    first_name: "Hodan",
    last_name: "Thrussell",
    phone_number: 9891852895,
    email: "hthrussell@gmail.com",
  },
  {
    id: 16,
    username: "gcaivano",
    password: "password",
    role: "client",
    first_name: "Gioia",
    last_name: "Caivano",
    phone_number: 2423341576,
    email: "gcaivano@gmail.com",
  },
  {
    id: 17,
    username: "skumar",
    password: "password",
    role: "client",
    first_name: "Scorpius",
    last_name: "Kumar",
    phone_number: 7735205858,
    email: "skumar@gmail.com",
  },
  {
    id: 18,
    username: "thayter",
    password: "password",
    role: "client",
    first_name: "Thalassa",
    last_name: "Hayter",
    phone_number: 6285012151,
    email: "thayter@gmail.com",
  },
  {
    id: 19,
    username: "dricchetti",
    password: "password",
    role: "client",
    first_name: "Dirk",
    last_name: "Ricchetti",
    phone_number: 5998260307,
    email: "dricchetti@gmail.com",
  },
  {
    id: 20,
    username: "zlippi",
    password: "password",
    role: "client",
    first_name: "Zerachiel",
    last_name: "Lippi",
    phone_number: 3171817583,
    email: "zlippi@gmail.com",
  },
];
